// Copyright (c) 2018-2020 MobileCoin Inc.

// MUST BE KEPT IN SYNC WITH RUST CODE!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: external.proto

package block

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

/// The result code indicating whether the timestamp was found, can be tried again later, or will
/// never be found with the current configuration of the service offering timestamps via the watcher.
type TimestampResultCode int32

const (
	/// The default value for fixed32 is intentionally unused to avoid omitting this field.
	TimestampResultCode_UnusedField TimestampResultCode = 0
	/// The timestamp was found for at least one watched consensus validator.
	TimestampResultCode_TimestampFound TimestampResultCode = 1
	/// The timestamp was not found, but the watcher sync is behind for at least one watched consensus
	/// validator. It is possible that the timestamp will be available once the watcher is fully synced.
	TimestampResultCode_WatcherBehind TimestampResultCode = 2
	/// The timestamp cannot be known with the service's current watcher configuration.
	/// In this case, the watcher must be restarted to include in its watched URLs a sufficient
	/// set of consensus validators so that at least one of those validators participated in
	/// consensus for every block.
	TimestampResultCode_Unavailable TimestampResultCode = 3
	/// A WatcherDBError occurred when getting signatures and timestamps.
	TimestampResultCode_WatcherDatabaseError TimestampResultCode = 4
	/// A timestamp was requested for a block index out of bounds, e.g. 0.
	TimestampResultCode_BlockIndexOutOfBounds TimestampResultCode = 5
)

// Enum value maps for TimestampResultCode.
var (
	TimestampResultCode_name = map[int32]string{
		0: "UnusedField",
		1: "TimestampFound",
		2: "WatcherBehind",
		3: "Unavailable",
		4: "WatcherDatabaseError",
		5: "BlockIndexOutOfBounds",
	}
	TimestampResultCode_value = map[string]int32{
		"UnusedField":           0,
		"TimestampFound":        1,
		"WatcherBehind":         2,
		"Unavailable":           3,
		"WatcherDatabaseError":  4,
		"BlockIndexOutOfBounds": 5,
	}
)

func (x TimestampResultCode) Enum() *TimestampResultCode {
	p := new(TimestampResultCode)
	*p = x
	return p
}

func (x TimestampResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimestampResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_external_proto_enumTypes[0].Descriptor()
}

func (TimestampResultCode) Type() protoreflect.EnumType {
	return &file_external_proto_enumTypes[0]
}

func (x TimestampResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimestampResultCode.Descriptor instead.
func (TimestampResultCode) EnumDescriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{0}
}

/// A Ristretto private key.
type RistrettoPrivate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RistrettoPrivate) Reset() {
	*x = RistrettoPrivate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RistrettoPrivate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RistrettoPrivate) ProtoMessage() {}

func (x *RistrettoPrivate) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RistrettoPrivate.ProtoReflect.Descriptor instead.
func (*RistrettoPrivate) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{0}
}

func (x *RistrettoPrivate) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

/// A 32-byte compressed Ristretto curve point (public key)
type CompressedRistretto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CompressedRistretto) Reset() {
	*x = CompressedRistretto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompressedRistretto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressedRistretto) ProtoMessage() {}

func (x *CompressedRistretto) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressedRistretto.ProtoReflect.Descriptor instead.
func (*CompressedRistretto) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{1}
}

func (x *CompressedRistretto) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

/// An Ed25519 public key, for validating signatures.
type Ed25519Public struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Ed25519Public) Reset() {
	*x = Ed25519Public{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ed25519Public) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ed25519Public) ProtoMessage() {}

func (x *Ed25519Public) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ed25519Public.ProtoReflect.Descriptor instead.
func (*Ed25519Public) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{2}
}

func (x *Ed25519Public) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

/// An Ed25519 signature object
type Ed25519Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Ed25519Signature) Reset() {
	*x = Ed25519Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ed25519Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ed25519Signature) ProtoMessage() {}

func (x *Ed25519Signature) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ed25519Signature.ProtoReflect.Descriptor instead.
func (*Ed25519Signature) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{3}
}

func (x *Ed25519Signature) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

/// Complete AccountKey, containing the pair of secret keys, which can be used
/// for spending, and optionally some Fog related info that is used to form
/// public addresses for accounts that sign up with Fog service.
///
/// This matches the Rust `transaction::AccountKey` struct.
type AccountKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	/// Private key 'a' used for view-key matching.
	ViewPrivateKey *RistrettoPrivate `protobuf:"bytes,1,opt,name=view_private_key,json=viewPrivateKey,proto3" json:"view_private_key,omitempty"`
	/// Private key `b` used for spending.
	SpendPrivateKey *RistrettoPrivate `protobuf:"bytes,2,opt,name=spend_private_key,json=spendPrivateKey,proto3" json:"spend_private_key,omitempty"`
	/// Optional url of fog report server.
	/// Empty string when not in use, i.e. for accounts that don't have fog service.
	FogReportUrl string `protobuf:"bytes,3,opt,name=fog_report_url,json=fogReportUrl,proto3" json:"fog_report_url,omitempty"`
	/// Optional fog report id.
	/// The fog report server may serve multiple reports, this id disambiguates
	/// which one to use when sending to this account.
	FogReportId string `protobuf:"bytes,4,opt,name=fog_report_id,json=fogReportId,proto3" json:"fog_report_id,omitempty"`
	/// Optional fingerprint of fog authority key.
	/// Empty when not in use.
	FogAuthorityFingerprint []byte `protobuf:"bytes,5,opt,name=fog_authority_fingerprint,json=fogAuthorityFingerprint,proto3" json:"fog_authority_fingerprint,omitempty"`
}

func (x *AccountKey) Reset() {
	*x = AccountKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountKey) ProtoMessage() {}

func (x *AccountKey) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountKey.ProtoReflect.Descriptor instead.
func (*AccountKey) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{4}
}

func (x *AccountKey) GetViewPrivateKey() *RistrettoPrivate {
	if x != nil {
		return x.ViewPrivateKey
	}
	return nil
}

func (x *AccountKey) GetSpendPrivateKey() *RistrettoPrivate {
	if x != nil {
		return x.SpendPrivateKey
	}
	return nil
}

func (x *AccountKey) GetFogReportUrl() string {
	if x != nil {
		return x.FogReportUrl
	}
	return ""
}

func (x *AccountKey) GetFogReportId() string {
	if x != nil {
		return x.FogReportId
	}
	return ""
}

func (x *AccountKey) GetFogAuthorityFingerprint() []byte {
	if x != nil {
		return x.FogAuthorityFingerprint
	}
	return nil
}

/// A public address, used to identify recipients.
type PublicAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	/// View public key
	ViewPublicKey *CompressedRistretto `protobuf:"bytes,1,opt,name=view_public_key,json=viewPublicKey,proto3" json:"view_public_key,omitempty"`
	/// Spend public key
	SpendPublicKey *CompressedRistretto `protobuf:"bytes,2,opt,name=spend_public_key,json=spendPublicKey,proto3" json:"spend_public_key,omitempty"`
	/// Optional url of fog report server.
	/// Empty string when not in use, i.e. for accounts that don't have fog service.
	/// Indicates the place at which the fog report server should be contacted.
	FogReportUrl string `protobuf:"bytes,3,opt,name=fog_report_url,json=fogReportUrl,proto3" json:"fog_report_url,omitempty"`
	/// Optional fog report id.
	/// The fog report server may serve multiple reports, this id disambiguates
	/// which one to use when sending to this account.
	FogReportId string `protobuf:"bytes,4,opt,name=fog_report_id,json=fogReportId,proto3" json:"fog_report_id,omitempty"`
	/// Signature of fog authority fingerprint using private key which
	/// corresponds to view_public_key.
	/// This should be a Schnorrkel signature.
	FogAuthorityFingerprintSig []byte `protobuf:"bytes,5,opt,name=fog_authority_fingerprint_sig,json=fogAuthorityFingerprintSig,proto3" json:"fog_authority_fingerprint_sig,omitempty"`
}

func (x *PublicAddress) Reset() {
	*x = PublicAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicAddress) ProtoMessage() {}

func (x *PublicAddress) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicAddress.ProtoReflect.Descriptor instead.
func (*PublicAddress) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{5}
}

func (x *PublicAddress) GetViewPublicKey() *CompressedRistretto {
	if x != nil {
		return x.ViewPublicKey
	}
	return nil
}

func (x *PublicAddress) GetSpendPublicKey() *CompressedRistretto {
	if x != nil {
		return x.SpendPublicKey
	}
	return nil
}

func (x *PublicAddress) GetFogReportUrl() string {
	if x != nil {
		return x.FogReportUrl
	}
	return ""
}

func (x *PublicAddress) GetFogReportId() string {
	if x != nil {
		return x.FogReportId
	}
	return ""
}

func (x *PublicAddress) GetFogAuthorityFingerprintSig() []byte {
	if x != nil {
		return x.FogAuthorityFingerprintSig
	}
	return nil
}

/// A KDF can be used to stretch a 32 byte secret into multiple secret private keys.
/// The RootIdentity is a compact form of a user's account key, if it has been
/// derived in this way. This may be useful for e.g. paper wallets.
type RootIdentity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	/// The root entropy used to derive cryptonote private keys for this account
	RootEntropy *RootEntropy `protobuf:"bytes,1,opt,name=root_entropy,json=rootEntropy,proto3" json:"root_entropy,omitempty"`
	/// Optional url of fog report server, same as in AccountKey
	FogReportUrl string `protobuf:"bytes,2,opt,name=fog_report_url,json=fogReportUrl,proto3" json:"fog_report_url,omitempty"`
	/// Optional fog report id, same as in AccountKey
	FogReportId string `protobuf:"bytes,3,opt,name=fog_report_id,json=fogReportId,proto3" json:"fog_report_id,omitempty"`
	/// Optional fingerprint of fog authority key.
	/// Empty when not in use.
	FogAuthorityFingerprint []byte `protobuf:"bytes,5,opt,name=fog_authority_fingerprint,json=fogAuthorityFingerprint,proto3" json:"fog_authority_fingerprint,omitempty"`
}

func (x *RootIdentity) Reset() {
	*x = RootIdentity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootIdentity) ProtoMessage() {}

func (x *RootIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootIdentity.ProtoReflect.Descriptor instead.
func (*RootIdentity) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{6}
}

func (x *RootIdentity) GetRootEntropy() *RootEntropy {
	if x != nil {
		return x.RootEntropy
	}
	return nil
}

func (x *RootIdentity) GetFogReportUrl() string {
	if x != nil {
		return x.FogReportUrl
	}
	return ""
}

func (x *RootIdentity) GetFogReportId() string {
	if x != nil {
		return x.FogReportId
	}
	return ""
}

func (x *RootIdentity) GetFogAuthorityFingerprint() []byte {
	if x != nil {
		return x.FogAuthorityFingerprint
	}
	return nil
}

/// A 32 byte secret used as input key material to derive private keys
type RootEntropy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RootEntropy) Reset() {
	*x = RootEntropy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootEntropy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootEntropy) ProtoMessage() {}

func (x *RootEntropy) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootEntropy.ProtoReflect.Descriptor instead.
func (*RootEntropy) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{7}
}

func (x *RootEntropy) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

/// A ViewKey is a reduced AccountKey -- it contains the private key necessary to
/// view your transactions and see the amounts, but not to send new transactions.
/// This concept is part of Cryptonote.
/// In Mobilecoin, all public addresses correspond to subaddresses, and often
/// the "default subaddress" is used.
/// The ViewKey similarly corresponds to a particular subaddress.
type ViewKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	/// The view-private-key of the account. This enables to check if a transaction
	/// corresponds to this subaddress, and to interact with fog.
	ViewPrivateKey *RistrettoPrivate `protobuf:"bytes,1,opt,name=view_private_key,json=viewPrivateKey,proto3" json:"view_private_key,omitempty"`
	/// The spend public key of the account.
	/// This value also appears in the public address.
	SpendPublicKey *CompressedRistretto `protobuf:"bytes,2,opt,name=spend_public_key,json=spendPublicKey,proto3" json:"spend_public_key,omitempty"`
}

func (x *ViewKey) Reset() {
	*x = ViewKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewKey) ProtoMessage() {}

func (x *ViewKey) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewKey.ProtoReflect.Descriptor instead.
func (*ViewKey) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{8}
}

func (x *ViewKey) GetViewPrivateKey() *RistrettoPrivate {
	if x != nil {
		return x.ViewPrivateKey
	}
	return nil
}

func (x *ViewKey) GetSpendPublicKey() *CompressedRistretto {
	if x != nil {
		return x.SpendPublicKey
	}
	return nil
}

/// A 32-byte scalar associated to the ristretto group.
/// This is the same as RistrettoPrivate, but they are used in different places.
/// TODO: MC-1605 Consider to factor out this type, or just this proto message.
type CurveScalar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CurveScalar) Reset() {
	*x = CurveScalar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurveScalar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurveScalar) ProtoMessage() {}

func (x *CurveScalar) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurveScalar.ProtoReflect.Descriptor instead.
func (*CurveScalar) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{9}
}

func (x *CurveScalar) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

/// A 32-byte mobilecoin transaction key image.
type KeyImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *KeyImage) Reset() {
	*x = KeyImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyImage) ProtoMessage() {}

func (x *KeyImage) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyImage.ProtoReflect.Descriptor instead.
func (*KeyImage) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{10}
}

func (x *KeyImage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From uint64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   uint64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *Range) Reset() {
	*x = Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{11}
}

func (x *Range) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Range) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

type TxOutMembershipHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TxOutMembershipHash) Reset() {
	*x = TxOutMembershipHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxOutMembershipHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutMembershipHash) ProtoMessage() {}

func (x *TxOutMembershipHash) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutMembershipHash.ProtoReflect.Descriptor instead.
func (*TxOutMembershipHash) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{12}
}

func (x *TxOutMembershipHash) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TxOutMembershipElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Range *Range               `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	Hash  *TxOutMembershipHash `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *TxOutMembershipElement) Reset() {
	*x = TxOutMembershipElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxOutMembershipElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutMembershipElement) ProtoMessage() {}

func (x *TxOutMembershipElement) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutMembershipElement.ProtoReflect.Descriptor instead.
func (*TxOutMembershipElement) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{13}
}

func (x *TxOutMembershipElement) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *TxOutMembershipElement) GetHash() *TxOutMembershipHash {
	if x != nil {
		return x.Hash
	}
	return nil
}

type TxOutMembershipProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index        uint64                    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	HighestIndex uint64                    `protobuf:"varint,2,opt,name=highest_index,json=highestIndex,proto3" json:"highest_index,omitempty"`
	Elements     []*TxOutMembershipElement `protobuf:"bytes,3,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *TxOutMembershipProof) Reset() {
	*x = TxOutMembershipProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxOutMembershipProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutMembershipProof) ProtoMessage() {}

func (x *TxOutMembershipProof) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutMembershipProof.ProtoReflect.Descriptor instead.
func (*TxOutMembershipProof) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{14}
}

func (x *TxOutMembershipProof) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TxOutMembershipProof) GetHighestIndex() uint64 {
	if x != nil {
		return x.HighestIndex
	}
	return 0
}

func (x *TxOutMembershipProof) GetElements() []*TxOutMembershipElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

// A hash of the shared secret of a transaction output.
//
// Can be used by the recipient of a transaction output to verify that the
// bearer of this number knew the shared secret of the transaction output,
// thereby providing evidence that they are the sender.
type TxOutConfirmationNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *TxOutConfirmationNumber) Reset() {
	*x = TxOutConfirmationNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxOutConfirmationNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutConfirmationNumber) ProtoMessage() {}

func (x *TxOutConfirmationNumber) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutConfirmationNumber.ProtoReflect.Descriptor instead.
func (*TxOutConfirmationNumber) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{15}
}

func (x *TxOutConfirmationNumber) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Amount.
type Amount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A Pedersen commitment `v*G + s*H`
	Commitment *CompressedRistretto `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// `masked_value = value XOR_8 Blake2B("value_mask" || shared_secret)`
	MaskedValue uint64 `protobuf:"fixed64,2,opt,name=masked_value,json=maskedValue,proto3" json:"masked_value,omitempty"`
}

func (x *Amount) Reset() {
	*x = Amount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{16}
}

func (x *Amount) GetCommitment() *CompressedRistretto {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *Amount) GetMaskedValue() uint64 {
	if x != nil {
		return x.MaskedValue
	}
	return 0
}

type EncryptedFogHint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EncryptedFogHint) Reset() {
	*x = EncryptedFogHint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptedFogHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedFogHint) ProtoMessage() {}

func (x *EncryptedFogHint) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedFogHint.ProtoReflect.Descriptor instead.
func (*EncryptedFogHint) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{17}
}

func (x *EncryptedFogHint) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// A Transaction Output.
type TxOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Amount.
	Amount *Amount `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Public key.
	TargetKey *CompressedRistretto `protobuf:"bytes,2,opt,name=target_key,json=targetKey,proto3" json:"target_key,omitempty"`
	// Public key.
	PublicKey *CompressedRistretto `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Encrypted fog hint payload.
	// This is an mc-crypto-box cryptogram for the fog ingest server,
	// or a random cryptogram indistinguishable from a real one.
	EFogHint *EncryptedFogHint `protobuf:"bytes,4,opt,name=e_fog_hint,json=eFogHint,proto3" json:"e_fog_hint,omitempty"`
}

func (x *TxOut) Reset() {
	*x = TxOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOut) ProtoMessage() {}

func (x *TxOut) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOut.ProtoReflect.Descriptor instead.
func (*TxOut) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{18}
}

func (x *TxOut) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *TxOut) GetTargetKey() *CompressedRistretto {
	if x != nil {
		return x.TargetKey
	}
	return nil
}

func (x *TxOut) GetPublicKey() *CompressedRistretto {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *TxOut) GetEFogHint() *EncryptedFogHint {
	if x != nil {
		return x.EFogHint
	}
	return nil
}

type TxIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// "Ring" of inputs, one of which is actually being spent.
	Ring []*TxOut `protobuf:"bytes,1,rep,name=ring,proto3" json:"ring,omitempty"`
	// Proof that each TxOut in `ring` is in the ledger.
	Proofs []*TxOutMembershipProof `protobuf:"bytes,2,rep,name=proofs,proto3" json:"proofs,omitempty"`
}

func (x *TxIn) Reset() {
	*x = TxIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxIn) ProtoMessage() {}

func (x *TxIn) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxIn.ProtoReflect.Descriptor instead.
func (*TxIn) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{19}
}

func (x *TxIn) GetRing() []*TxOut {
	if x != nil {
		return x.Ring
	}
	return nil
}

func (x *TxIn) GetProofs() []*TxOutMembershipProof {
	if x != nil {
		return x.Proofs
	}
	return nil
}

// A transaction that a client submits to consensus
type TxPrefix struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Transaction inputs.
	Inputs []*TxIn `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Transaction outputs.
	Outputs []*TxOut `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	// Fee paid to the foundation for this transaction
	Fee uint64 `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	// The block index at which this transaction is no longer valid.
	TombstoneBlock uint64 `protobuf:"varint,4,opt,name=tombstone_block,json=tombstoneBlock,proto3" json:"tombstone_block,omitempty"`
}

func (x *TxPrefix) Reset() {
	*x = TxPrefix{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxPrefix) ProtoMessage() {}

func (x *TxPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxPrefix.ProtoReflect.Descriptor instead.
func (*TxPrefix) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{20}
}

func (x *TxPrefix) GetInputs() []*TxIn {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *TxPrefix) GetOutputs() []*TxOut {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *TxPrefix) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TxPrefix) GetTombstoneBlock() uint64 {
	if x != nil {
		return x.TombstoneBlock
	}
	return 0
}

type RingMLSAG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CZero     *CurveScalar   `protobuf:"bytes,1,opt,name=c_zero,json=cZero,proto3" json:"c_zero,omitempty"`
	Responses []*CurveScalar `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	KeyImage  *KeyImage      `protobuf:"bytes,3,opt,name=key_image,json=keyImage,proto3" json:"key_image,omitempty"`
}

func (x *RingMLSAG) Reset() {
	*x = RingMLSAG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RingMLSAG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingMLSAG) ProtoMessage() {}

func (x *RingMLSAG) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingMLSAG.ProtoReflect.Descriptor instead.
func (*RingMLSAG) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{21}
}

func (x *RingMLSAG) GetCZero() *CurveScalar {
	if x != nil {
		return x.CZero
	}
	return nil
}

func (x *RingMLSAG) GetResponses() []*CurveScalar {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *RingMLSAG) GetKeyImage() *KeyImage {
	if x != nil {
		return x.KeyImage
	}
	return nil
}

type SignatureRctBulletproofs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RingSignatures          []*RingMLSAG           `protobuf:"bytes,1,rep,name=ring_signatures,json=ringSignatures,proto3" json:"ring_signatures,omitempty"`
	PseudoOutputCommitments []*CompressedRistretto `protobuf:"bytes,2,rep,name=pseudo_output_commitments,json=pseudoOutputCommitments,proto3" json:"pseudo_output_commitments,omitempty"`
	RangeProofs             []byte                 `protobuf:"bytes,3,opt,name=range_proofs,json=rangeProofs,proto3" json:"range_proofs,omitempty"`
}

func (x *SignatureRctBulletproofs) Reset() {
	*x = SignatureRctBulletproofs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignatureRctBulletproofs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureRctBulletproofs) ProtoMessage() {}

func (x *SignatureRctBulletproofs) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureRctBulletproofs.ProtoReflect.Descriptor instead.
func (*SignatureRctBulletproofs) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{22}
}

func (x *SignatureRctBulletproofs) GetRingSignatures() []*RingMLSAG {
	if x != nil {
		return x.RingSignatures
	}
	return nil
}

func (x *SignatureRctBulletproofs) GetPseudoOutputCommitments() []*CompressedRistretto {
	if x != nil {
		return x.PseudoOutputCommitments
	}
	return nil
}

func (x *SignatureRctBulletproofs) GetRangeProofs() []byte {
	if x != nil {
		return x.RangeProofs
	}
	return nil
}

type Tx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The actual contents of the transaction.
	Prefix *TxPrefix `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// The RingCT signature on the prefix.
	Signature *SignatureRctBulletproofs `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Tx) Reset() {
	*x = Tx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tx) ProtoMessage() {}

func (x *Tx) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tx.ProtoReflect.Descriptor instead.
func (*Tx) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{23}
}

func (x *Tx) GetPrefix() *TxPrefix {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *Tx) GetSignature() *SignatureRctBulletproofs {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TxHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Hash of a single transaction.
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *TxHash) Reset() {
	*x = TxHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxHash) ProtoMessage() {}

func (x *TxHash) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxHash.ProtoReflect.Descriptor instead.
func (*TxHash) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{24}
}

func (x *TxHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Given to the recipient of a transaction output by the sender so that the
// recipient may verify that the other party is indeed the sender.
//
// Often given to the recipient before the transaction is finalized so that
// the recipient may know to anticipate the arrival of a transaction output,
// as well as know who it's from, when to consider it as having surpassed
// the tombstone block, and the expected amount of the output.
type Receipt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Public key of the TxOut.
	PublicKey *CompressedRistretto `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Confirmation number of the TxOut.
	Confirmation *TxOutConfirmationNumber `protobuf:"bytes,2,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	// Tombstone block of the Tx that produced the TxOut.
	// Note: This value is self-reported by the sender and is unverifiable.
	TombstoneBlock uint64 `protobuf:"varint,3,opt,name=tombstone_block,json=tombstoneBlock,proto3" json:"tombstone_block,omitempty"`
	// Amount of the TxOut.
	// Note: This value is self-reported by the sender and is unverifiable.
	Amount *Amount `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_external_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{25}
}

func (x *Receipt) GetPublicKey() *CompressedRistretto {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Receipt) GetConfirmation() *TxOutConfirmationNumber {
	if x != nil {
		return x.Confirmation
	}
	return nil
}

func (x *Receipt) GetTombstoneBlock() uint64 {
	if x != nil {
		return x.TombstoneBlock
	}
	return 0
}

func (x *Receipt) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

var File_external_proto protoreflect.FileDescriptor

var file_external_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x22, 0x26, 0x0a, 0x10, 0x52, 0x69,
	0x73, 0x74, 0x72, 0x65, 0x74, 0x74, 0x6f, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x29, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64,
	0x52, 0x69, 0x73, 0x74, 0x72, 0x65, 0x74, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x23, 0x0a,
	0x0d, 0x45, 0x64, 0x32, 0x35, 0x35, 0x31, 0x39, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x26, 0x0a, 0x10, 0x45, 0x64, 0x32, 0x35, 0x35, 0x31, 0x39, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa0, 0x02, 0x0a, 0x0a, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x44, 0x0a, 0x10, 0x76, 0x69, 0x65,
	0x77, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x52,
	0x69, 0x73, 0x74, 0x72, 0x65, 0x74, 0x74, 0x6f, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52,
	0x0e, 0x76, 0x69, 0x65, 0x77, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x46, 0x0a, 0x11, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x52, 0x69, 0x73, 0x74, 0x72, 0x65, 0x74, 0x74, 0x6f, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x0f, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x6f, 0x67, 0x5f, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x66, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x22, 0x0a,
	0x0d, 0x66, 0x6f, 0x67, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49,
	0x64, 0x12, 0x3a, 0x0a, 0x19, 0x66, 0x6f, 0x67, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x17, 0x66, 0x6f, 0x67, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x22, 0xac, 0x02,
	0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x45, 0x0a, 0x0f, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x69,
	0x73, 0x74, 0x72, 0x65, 0x74, 0x74, 0x6f, 0x52, 0x0d, 0x76, 0x69, 0x65, 0x77, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x47, 0x0a, 0x10, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x5f,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x69, 0x73, 0x74, 0x72, 0x65, 0x74, 0x74, 0x6f, 0x52,
	0x0e, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12,
	0x24, 0x0a, 0x0e, 0x66, 0x6f, 0x67, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x22, 0x0a, 0x0d, 0x66, 0x6f, 0x67, 0x5f, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x6f,
	0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x1d, 0x66, 0x6f, 0x67,
	0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x1a, 0x66, 0x6f, 0x67, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x46, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x53, 0x69, 0x67, 0x22, 0xce, 0x01, 0x0a,
	0x0c, 0x52, 0x6f, 0x6f, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x38, 0x0a,
	0x0c, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x70, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x52,
	0x6f, 0x6f, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x6f, 0x70, 0x79, 0x52, 0x0b, 0x72, 0x6f, 0x6f, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x6f, 0x70, 0x79, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x6f, 0x67, 0x5f, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x66, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x22, 0x0a,
	0x0d, 0x66, 0x6f, 0x67, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x6f, 0x67, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49,
	0x64, 0x12, 0x3a, 0x0a, 0x19, 0x66, 0x6f, 0x67, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x17, 0x66, 0x6f, 0x67, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x22, 0x21, 0x0a,
	0x0b, 0x52, 0x6f, 0x6f, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x6f, 0x70, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x98, 0x01, 0x0a, 0x07, 0x56, 0x69, 0x65, 0x77, 0x4b, 0x65, 0x79, 0x12, 0x44, 0x0a, 0x10,
	0x76, 0x69, 0x65, 0x77, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x52, 0x69, 0x73, 0x74, 0x72, 0x65, 0x74, 0x74, 0x6f, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x52, 0x0e, 0x76, 0x69, 0x65, 0x77, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x12, 0x47, 0x0a, 0x10, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x64, 0x52, 0x69, 0x73, 0x74, 0x72, 0x65, 0x74, 0x74, 0x6f, 0x52, 0x0e, 0x73, 0x70, 0x65,
	0x6e, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x21, 0x0a, 0x0b, 0x43,
	0x75, 0x72, 0x76, 0x65, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1e,
	0x0a, 0x08, 0x4b, 0x65, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2b,
	0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x13, 0x54,
	0x78, 0x4f, 0x75, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x72, 0x0a, 0x16, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x25, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x48, 0x61, 0x73, 0x68, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x8f, 0x01, 0x0a, 0x14, 0x54,
	0x78, 0x4f, 0x75, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x69, 0x67,
	0x68, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x3c,
	0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x54, 0x78, 0x4f, 0x75,
	0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x2d, 0x0a, 0x17,
	0x54, 0x78, 0x4f, 0x75, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x6a, 0x0a, 0x06, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52,
	0x69, 0x73, 0x74, 0x72, 0x65, 0x74, 0x74, 0x6f, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0b, 0x6d, 0x61, 0x73, 0x6b,
	0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x26, 0x0a, 0x10, 0x45, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x65, 0x64, 0x46, 0x6f, 0x67, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0xe7, 0x01, 0x0a, 0x05, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x69, 0x73,
	0x74, 0x72, 0x65, 0x74, 0x74, 0x6f, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4b, 0x65,
	0x79, 0x12, 0x3c, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x69, 0x73, 0x74, 0x72,
	0x65, 0x74, 0x74, 0x6f, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12,
	0x38, 0x0a, 0x0a, 0x65, 0x5f, 0x66, 0x6f, 0x67, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x46, 0x6f, 0x67, 0x48, 0x69, 0x6e, 0x74, 0x52,
	0x08, 0x65, 0x46, 0x6f, 0x67, 0x48, 0x69, 0x6e, 0x74, 0x22, 0x63, 0x0a, 0x04, 0x54, 0x78, 0x49,
	0x6e, 0x12, 0x23, 0x0a, 0x04, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x54, 0x78, 0x4f, 0x75, 0x74,
	0x52, 0x04, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x36, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x73, 0x22, 0x98,
	0x01, 0x0a, 0x08, 0x54, 0x78, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x26, 0x0a, 0x06, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x54, 0x78, 0x49, 0x6e, 0x52, 0x06, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e,
	0x54, 0x78, 0x4f, 0x75, 0x74, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x66, 0x65, 0x65,
	0x12, 0x27, 0x0a, 0x0f, 0x74, 0x6f, 0x6d, 0x62, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x5f, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x74, 0x6f, 0x6d, 0x62, 0x73,
	0x74, 0x6f, 0x6e, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x9f, 0x01, 0x0a, 0x09, 0x52, 0x69,
	0x6e, 0x67, 0x4d, 0x4c, 0x53, 0x41, 0x47, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x5f, 0x7a, 0x65, 0x72,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x43, 0x75, 0x72, 0x76, 0x65, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x52, 0x05,
	0x63, 0x5a, 0x65, 0x72, 0x6f, 0x12, 0x33, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2e, 0x43, 0x75, 0x72, 0x76, 0x65, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x52,
	0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x6b, 0x65,
	0x79, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x4b, 0x65, 0x79, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x18,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x63, 0x74, 0x42, 0x75, 0x6c, 0x6c,
	0x65, 0x74, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x73, 0x12, 0x3c, 0x0a, 0x0f, 0x72, 0x69, 0x6e, 0x67,
	0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x52, 0x69, 0x6e,
	0x67, 0x4d, 0x4c, 0x53, 0x41, 0x47, 0x52, 0x0e, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x59, 0x0a, 0x19, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f,
	0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52,
	0x69, 0x73, 0x74, 0x72, 0x65, 0x74, 0x74, 0x6f, 0x52, 0x17, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x73, 0x22, 0x72, 0x0a, 0x02, 0x54, 0x78, 0x12, 0x2a, 0x0a, 0x06, 0x70, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x54, 0x78, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x06,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x40, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x63,
	0x74, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x73, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x1c, 0x0a, 0x06, 0x54, 0x78, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0xe1, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x12, 0x3c, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x69, 0x73, 0x74,
	0x72, 0x65, 0x74, 0x74, 0x6f, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x12, 0x45, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x6f, 0x6d, 0x62, 0x73,
	0x74, 0x6f, 0x6e, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0e, 0x74, 0x6f, 0x6d, 0x62, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x12, 0x28, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x93, 0x01, 0x0a, 0x13, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e, 0x75, 0x73, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x72, 0x42, 0x65, 0x68, 0x69, 0x6e, 0x64, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x6e,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x4f, 0x75, 0x74, 0x4f, 0x66, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x10, 0x05,
	0x42, 0x2a, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x63, 0x6f,
	0x69, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x42, 0x0d, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x43, 0x6f,
	0x69, 0x6e, 0x41, 0x50, 0x49, 0x5a, 0x05, 0x2e, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_external_proto_rawDescOnce sync.Once
	file_external_proto_rawDescData = file_external_proto_rawDesc
)

func file_external_proto_rawDescGZIP() []byte {
	file_external_proto_rawDescOnce.Do(func() {
		file_external_proto_rawDescData = protoimpl.X.CompressGZIP(file_external_proto_rawDescData)
	})
	return file_external_proto_rawDescData
}

var file_external_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_external_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_external_proto_goTypes = []interface{}{
	(TimestampResultCode)(0),         // 0: external.TimestampResultCode
	(*RistrettoPrivate)(nil),         // 1: external.RistrettoPrivate
	(*CompressedRistretto)(nil),      // 2: external.CompressedRistretto
	(*Ed25519Public)(nil),            // 3: external.Ed25519Public
	(*Ed25519Signature)(nil),         // 4: external.Ed25519Signature
	(*AccountKey)(nil),               // 5: external.AccountKey
	(*PublicAddress)(nil),            // 6: external.PublicAddress
	(*RootIdentity)(nil),             // 7: external.RootIdentity
	(*RootEntropy)(nil),              // 8: external.RootEntropy
	(*ViewKey)(nil),                  // 9: external.ViewKey
	(*CurveScalar)(nil),              // 10: external.CurveScalar
	(*KeyImage)(nil),                 // 11: external.KeyImage
	(*Range)(nil),                    // 12: external.Range
	(*TxOutMembershipHash)(nil),      // 13: external.TxOutMembershipHash
	(*TxOutMembershipElement)(nil),   // 14: external.TxOutMembershipElement
	(*TxOutMembershipProof)(nil),     // 15: external.TxOutMembershipProof
	(*TxOutConfirmationNumber)(nil),  // 16: external.TxOutConfirmationNumber
	(*Amount)(nil),                   // 17: external.Amount
	(*EncryptedFogHint)(nil),         // 18: external.EncryptedFogHint
	(*TxOut)(nil),                    // 19: external.TxOut
	(*TxIn)(nil),                     // 20: external.TxIn
	(*TxPrefix)(nil),                 // 21: external.TxPrefix
	(*RingMLSAG)(nil),                // 22: external.RingMLSAG
	(*SignatureRctBulletproofs)(nil), // 23: external.SignatureRctBulletproofs
	(*Tx)(nil),                       // 24: external.Tx
	(*TxHash)(nil),                   // 25: external.TxHash
	(*Receipt)(nil),                  // 26: external.Receipt
}
var file_external_proto_depIdxs = []int32{
	1,  // 0: external.AccountKey.view_private_key:type_name -> external.RistrettoPrivate
	1,  // 1: external.AccountKey.spend_private_key:type_name -> external.RistrettoPrivate
	2,  // 2: external.PublicAddress.view_public_key:type_name -> external.CompressedRistretto
	2,  // 3: external.PublicAddress.spend_public_key:type_name -> external.CompressedRistretto
	8,  // 4: external.RootIdentity.root_entropy:type_name -> external.RootEntropy
	1,  // 5: external.ViewKey.view_private_key:type_name -> external.RistrettoPrivate
	2,  // 6: external.ViewKey.spend_public_key:type_name -> external.CompressedRistretto
	12, // 7: external.TxOutMembershipElement.range:type_name -> external.Range
	13, // 8: external.TxOutMembershipElement.hash:type_name -> external.TxOutMembershipHash
	14, // 9: external.TxOutMembershipProof.elements:type_name -> external.TxOutMembershipElement
	2,  // 10: external.Amount.commitment:type_name -> external.CompressedRistretto
	17, // 11: external.TxOut.amount:type_name -> external.Amount
	2,  // 12: external.TxOut.target_key:type_name -> external.CompressedRistretto
	2,  // 13: external.TxOut.public_key:type_name -> external.CompressedRistretto
	18, // 14: external.TxOut.e_fog_hint:type_name -> external.EncryptedFogHint
	19, // 15: external.TxIn.ring:type_name -> external.TxOut
	15, // 16: external.TxIn.proofs:type_name -> external.TxOutMembershipProof
	20, // 17: external.TxPrefix.inputs:type_name -> external.TxIn
	19, // 18: external.TxPrefix.outputs:type_name -> external.TxOut
	10, // 19: external.RingMLSAG.c_zero:type_name -> external.CurveScalar
	10, // 20: external.RingMLSAG.responses:type_name -> external.CurveScalar
	11, // 21: external.RingMLSAG.key_image:type_name -> external.KeyImage
	22, // 22: external.SignatureRctBulletproofs.ring_signatures:type_name -> external.RingMLSAG
	2,  // 23: external.SignatureRctBulletproofs.pseudo_output_commitments:type_name -> external.CompressedRistretto
	21, // 24: external.Tx.prefix:type_name -> external.TxPrefix
	23, // 25: external.Tx.signature:type_name -> external.SignatureRctBulletproofs
	2,  // 26: external.Receipt.public_key:type_name -> external.CompressedRistretto
	16, // 27: external.Receipt.confirmation:type_name -> external.TxOutConfirmationNumber
	17, // 28: external.Receipt.amount:type_name -> external.Amount
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_external_proto_init() }
func file_external_proto_init() {
	if File_external_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_external_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RistrettoPrivate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompressedRistretto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ed25519Public); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ed25519Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootIdentity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootEntropy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurveScalar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxOutMembershipHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxOutMembershipElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxOutMembershipProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxOutConfirmationNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Amount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptedFogHint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxPrefix); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RingMLSAG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignatureRctBulletproofs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_external_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Receipt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_external_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_external_proto_goTypes,
		DependencyIndexes: file_external_proto_depIdxs,
		EnumInfos:         file_external_proto_enumTypes,
		MessageInfos:      file_external_proto_msgTypes,
	}.Build()
	File_external_proto = out.File
	file_external_proto_rawDesc = nil
	file_external_proto_goTypes = nil
	file_external_proto_depIdxs = nil
}
